version: '2'

services:
  postgres:
    image: postgres:10.0
    ports:
      - "5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  app:
    depends_on:
      - 'postgres'
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    env_file:
      - '.env'
    ports:
      - "3000:3000"

volumes:
  postgres: