version: '3'

services:
  db:
    image: postgres:10.0
    ports:
      - '5432'
  api:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    depends_on:
      - db
  sneakers:
    build: .
    command: bundle exec rake sneakers:run
    volumes:
      - .:/app
    env_file:
      - '.env'
    depends_on:
      - api